added guard for 'basic' colourscheme

diff --git a/xcolo b/xcolo
--- a/xcolo
+++ b/xcolo
@@ -1,6 +1,11 @@
 #!/bin/bash
 # changes Xresources colourscheme and saves new value
 
+if [[ $1 == "basic" ]]; then
+    echo >&2 "$(basename $0): invalid colourscheme"
+    exit 1
+fi
+
 START=$(($(grep -n "#include.*Xcolours/basic" ~/.Xresources | cut -d ":" -f 1) + 1))
 
 if [[ $# -eq 0 ]]; then
